import { CarData } from './Car';

export interface LevelConfig {
  id: number;
  gridWidth: number;
  gridHeight: number;
  exitX: number;
  exitZ: number;
  cars: CarData[];
}

export const LEVELS: LevelConfig[] = [
  // Level 1 - Easy introduction
  {
    id: 1,
    gridWidth: 6,
    gridHeight: 6,
    exitX: 5,
    exitZ: 2,
    cars: [
      {
        id: 'main',
        gridX: 2,
        gridZ: 2,
        length: 2,
        isHorizontal: true,
        color: '#ff3333',
        isMain: true,
      },
      {
        id: 'car1',
        gridX: 4,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#3366ff',
      },
      {
        id: 'car2',
        gridX: 1,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#ffaa00',
      },
      {
        id: 'car3',
        gridX: 3,
        gridZ: 4,
        length: 2,
        isHorizontal: true,
        color: '#9933ff',
      },
    ],
  },

  // Level 2 - More cars
  {
    id: 2,
    gridWidth: 6,
    gridHeight: 6,
    exitX: 5,
    exitZ: 3,
    cars: [
      {
        id: 'main',
        gridX: 0,
        gridZ: 3,
        length: 2,
        isHorizontal: true,
        color: '#ff3333',
        isMain: true,
      },
      {
        id: 'car1',
        gridX: 2,
        gridZ: 1,
        length: 3,
        isHorizontal: false,
        color: '#3366ff',
      },
      {
        id: 'car2',
        gridX: 3,
        gridZ: 0,
        length: 2,
        isHorizontal: true,
        color: '#ffaa00',
      },
      {
        id: 'car3',
        gridX: 5,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#9933ff',
      },
      {
        id: 'car4',
        gridX: 0,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#00cc66',
      },
      {
        id: 'car5',
        gridX: 3,
        gridZ: 5,
        length: 2,
        isHorizontal: true,
        color: '#ff6699',
      },
    ],
  },

  // Level 3 - Tricky positioning
  {
    id: 3,
    gridWidth: 6,
    gridHeight: 6,
    exitX: 5,
    exitZ: 2,
    cars: [
      {
        id: 'main',
        gridX: 1,
        gridZ: 2,
        length: 2,
        isHorizontal: true,
        color: '#ff3333',
        isMain: true,
      },
      {
        id: 'car1',
        gridX: 0,
        gridZ: 0,
        length: 3,
        isHorizontal: false,
        color: '#3366ff',
      },
      {
        id: 'car2',
        gridX: 3,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#ffaa00',
      },
      {
        id: 'car3',
        gridX: 4,
        gridZ: 2,
        length: 3,
        isHorizontal: false,
        color: '#9933ff',
      },
      {
        id: 'car4',
        gridX: 1,
        gridZ: 4,
        length: 2,
        isHorizontal: true,
        color: '#00cc66',
      },
      {
        id: 'car5',
        gridX: 5,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#ff6699',
      },
      {
        id: 'car6',
        gridX: 1,
        gridZ: 0,
        length: 2,
        isHorizontal: true,
        color: '#00cccc',
      },
    ],
  },

  // Level 4 - More complex
  {
    id: 4,
    gridWidth: 6,
    gridHeight: 6,
    exitX: 5,
    exitZ: 3,
    cars: [
      {
        id: 'main',
        gridX: 0,
        gridZ: 3,
        length: 2,
        isHorizontal: true,
        color: '#ff3333',
        isMain: true,
      },
      {
        id: 'car1',
        gridX: 2,
        gridZ: 0,
        length: 3,
        isHorizontal: false,
        color: '#3366ff',
      },
      {
        id: 'car2',
        gridX: 3,
        gridZ: 3,
        length: 2,
        isHorizontal: false,
        color: '#ffaa00',
      },
      {
        id: 'car3',
        gridX: 0,
        gridZ: 1,
        length: 2,
        isHorizontal: true,
        color: '#9933ff',
      },
      {
        id: 'car4',
        gridX: 4,
        gridZ: 0,
        length: 3,
        isHorizontal: false,
        color: '#00cc66',
      },
      {
        id: 'car5',
        gridX: 0,
        gridZ: 5,
        length: 3,
        isHorizontal: true,
        color: '#ff6699',
      },
      {
        id: 'car6',
        gridX: 5,
        gridZ: 4,
        length: 2,
        isHorizontal: false,
        color: '#00cccc',
      },
      {
        id: 'car7',
        gridX: 3,
        gridZ: 5,
        length: 2,
        isHorizontal: true,
        color: '#ffcc00',
      },
    ],
  },

  // Level 5 - Challenging
  {
    id: 5,
    gridWidth: 6,
    gridHeight: 6,
    exitX: 5,
    exitZ: 2,
    cars: [
      {
        id: 'main',
        gridX: 0,
        gridZ: 2,
        length: 2,
        isHorizontal: true,
        color: '#ff3333',
        isMain: true,
      },
      {
        id: 'car1',
        gridX: 2,
        gridZ: 0,
        length: 2,
        isHorizontal: false,
        color: '#3366ff',
      },
      {
        id: 'car2',
        gridX: 3,
        gridZ: 1,
        length: 2,
        isHorizontal: false,
        color: '#ffaa00',
      },
      {
        id: 'car3',
        gridX: 4,
        gridZ: 0,
        length: 3,
        isHorizontal: false,
        color: '#9933ff',
      },
      {
        id: 'car4',
        gridX: 0,
        gridZ: 0,
        length: 2,
        isHorizontal: true,
        color: '#00cc66',
      },
      {
        id: 'car5',
        gridX: 5,
        gridZ: 3,
        length: 3,
        isHorizontal: false,
        color: '#ff6699',
      },
      {
        id: 'car6',
        gridX: 0,
        gridZ: 4,
        length: 3,
        isHorizontal: true,
        color: '#00cccc',
      },
      {
        id: 'car7',
        gridX: 3,
        gridZ: 3,
        length: 2,
        isHorizontal: true,
        color: '#ffcc00',
      },
      {
        id: 'car8',
        gridX: 1,
        gridZ: 3,
        length: 2,
        isHorizontal: false,
        color: '#cc66ff',
      },
    ],
  },
];
